import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { checkout } from "../checkout";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Physical NFTs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Buy physical Baby Doll</h1>

        <div className={styles.grid}>
          <div>
            <Image src="/baby.jpeg" alt="NFT" width={400} height={400} />
            <p>Very expensive art piece 1</p>
            <button
              onClick={() => {
                checkout({
                  lineItems: [
                    {
                      price: "price_1LvonzCBi5rQFo0PsJTI7lzS",
                      quantity: 1,
                    },
                  ],
                });
              }}
            >
              BUY NOW!
            </button>
          </div>
          <div>
            <Image src="/baby1.jpg" alt="NFT" width={400} height={400} />
            <p>Very expensive art piece 2</p>
            <button
              onClick={() => {
                checkout({
                  lineItems: [
                    {
                      price: "price_1LvophCBi5rQFo0PBem8fiAJ",
                      quantity: 1,
                    },
                  ],
                });
              }}
            >
              BUY NOW!
            </button>
          </div>
        </div>
      </main>
    </div>
  );
}
